authors = [
"Fabien Chouteau",
]
description = "An Ada USB stack for embedded devices"
licenses = "BSD-3-Clause"
maintainers = [
"Fabien Chouteau <chouteau@adacore.com>",
]
maintainers-logins = [
"Fabien-Chouteau",
]
name = "usb_embedded"
tags = [
"embedded",
"usb",
"hid",
"midi",
"nostd",
]
version = "1.0.1"
website = "https://github.com/Fabien-Chouteau/usb_embedded"
[configuration]
auto_gpr_with = true
disabled = false
generate_ada = true
generate_c = true
generate_gpr = true
output_dir = "config"
[configuration.variables]
[configuration.variables.Control_Buffer_Size]
default = 256
first = 256
last = 9223372036854775807
type = "Integer"
[configuration.variables.Event_Log_Buffer_Size]
default = 0
first = 0
last = 9223372036854775807
type = "Integer"
[configuration.variables.Max_Strings]
default = 10
first = 0
last = 9223372036854775807
type = "Integer"
[configuration.variables.String_Buffer_Size]
default = 256
first = 0
last = 9223372036854775807
type = "Integer"
[[depends-on]]
bbqueue = "^1.0.0"
hal = "^1.0.0"

